- hosts: web
  tasks:
  - name: Ansible create file if it doesn't exist example
    file:
      path: "/var/www/html/index.html"
      state: touch
  - name: add content to file 
    copy:
      dest: "/var/www/html/index.html"
      content:
        <html>
        <header><title>This is title KRISHNA</title></header>
        <body>
        Hello world KRISHNA
        </body>
        </html>
