- hosts: web
  tasks:
  - name: Create a file in wen server
    file:
      dest: /etc/xyz1.txt
      state:  touch
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
